### ISSUE TITLE
Can't login: 'You've reached the login attempt'

### ISSUE THREAD

**Issue by groenerik** [Isaksson/node-red-contrib-unifi#139]
I recently upgraded from an USG with a controller hosted on an RPI to an UCG Ultra running on UnifiOS 4.06.

Now my Node-Red (v3.1.3) automation is broken.

I used to have close to 10 instances of the Unifi node (0.3.17) running with update intervals of 20-30 seconds without any problems. After the migration to the UCG Ultra I get only "You've reached the login attempt limit" messages.

After reading the #136 case, I reduced the number of Unifi nodes to only one and temporarily lowered the update frequency to 4 hours. Even after rebooting the UCG and Node-Red, the error persists.

After searching for solutions I came across a [similar reported issue in a HomeAssistant implementation](https://github.com/home-assistant/core/issues/122438). There a solution was found in the handling of cookies: Replacing CookieJar with DummieCookieJar. That code base is Python, but I hope something similar can be applied here as well.

**Comment by Isaksson** [comment]
So you cant get a single command sent to your controller? you get the "You've reached the login attempt limit" error from the first try?

**Comment by groenerik** [comment]
That's right. After a Node-RED restart and triggering the flow, I see the node status flashing for half a second to green and a text with something like 'Logged in' and almost immediately changing to red and the message 'You've reached the login attempt limit'.

I checked the debug option, restarted Node-Red. Attached the Syslog.
[syslog.txt](https://github.com/user-attachments/files/17178551/syslog.txt)

Note: in the log I shortened the cookies (not sure if this is security sensitive). 

It seems like it returns 5 times a 401 status and then a 429.

For clarity I only inject one message to the node. (checked with a delay node and counter).

**Comment by Isaksson** [comment]
Ahh I understand, apparently they have made some changes for the new devices, I use same software version as you but with a Dream Router and it works.

Yeah, the reason you se multiple requests is that the node automatically tries to login.

What I need is access to the new hardware so that I could see what's actually goes wrong.

If you're interested in helping me with this then it would be great if you create a new admin account in your device and then send me the credentials, and then you make a port forward in your firewall so that I could connect and run logins against your device.

**Comment by Isaksson** [comment]
No update from user.
