### ISSUE TITLE
Version 7 Support?

### ISSUE THREAD

**Issue by meehab** [Isaksson/node-red-contrib-unifi#75]
Since upgrading to Unifi V7, my automations have stopped working (unifi v7.1.65)

![Screenshot 2022-06-30 at 12 18 04](https://user-images.githubusercontent.com/23459469/176664563-408be3d2-2fcd-43e3-a881-f51dc525ae86.png)

I see app.err.invalid when the node is called, ClientDevices command in this case.

I know from the readme that the node supports unifi up to v6. I assume the fact that I'm on v7 is the reason for this issue. Are there any plans to add v7 support, or another alternative?

**Comment by Isaksson** [comment]
I just updated my system to 7.1.67 and it works, did you update from an very old version of unifi? so that the issue is that you need to tick the Unifi OS box in the settings for this node?

**Comment by meehab** [comment]
Thanks for the response. I tend to apply incremental updates shortly after they are published, so no big jump in versions. Thought it's been a while since I used this automation, so I cannot pinpoint when the issue first emerged.

Anyway, toggle on of the UnifiOS checkbox resulted in a different error (api.err.LoginRequired, though I have entered the correct credentials. Anyway, toggling back and now the original issue has gone away, but the data I get back doesn't make much sense and my function routine is tripping up. I'll try to do some more debugging later in the week.

Thanks again.

**Comment by Isaksson** [comment]
Have you made some more tests?

**Comment by Damageplan1980** [comment]
Hi there,

I have the same problem with version 7.1.68.
The node says "api.err.LoginRequired".

I created a new Administrator for this, because my other user does have 2FA enabled.
I can login to the management UI with this user.

Any ideas how I can get this node working?

Thanks
Matthias

EDIT:
Problem solved. I don't know why, but I tried again 5 minutes ago and now it is working... I absolutely have no clue why...
